import type { INodeProperties } from 'n8n-workflow';

export const mnexiumProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		default: 'chat',
		description: 'Choose which Mnexium API area this node should use.',
		options: [
			{ name: 'Chat', value: 'chat', description: 'Message a model with Mnexium memory controls' },
			{ name: 'Chat History', value: 'history', description: 'List, read, or delete prior chats' },
			{ name: 'Memory', value: 'memory', description: 'Manage durable memory records' },
			{ name: 'Record', value: 'record', description: 'Create, query, and search typed records' },
			{ name: 'Record Schema', value: 'recordSchema', description: 'Define typed record schemas' },
			{ name: 'Claim', value: 'claim', description: 'Work with structured claims and truth state' },
			{ name: 'Profile', value: 'profile', description: 'Manage subject profile fields and schema' },
			{ name: 'State', value: 'state', description: 'Store and retrieve short-lived agent state' },
			{ name: 'System Prompt', value: 'prompt', description: 'Manage reusable system prompts' },
			{ name: 'Memory Policy', value: 'memoryPolicy', description: 'Configure and resolve memory policies' },
			{ name: 'Audit', value: 'audit', description: 'Inspect request/response traces' },
			{ name: 'Custom Request', value: 'custom', description: 'Call any Mnexium endpoint directly' },
		],
	},
	{
		displayName:
			'Send model requests with persistent context, memory recall, and conversation continuity. <a href="https://www.mnexium.com/docs#chat" target="_blank">Docs</a><hr />',
		name: 'resourceHelpChat',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['chat'] } },
	},
	{
		displayName:
			'Work with saved conversations so you can inspect, continue, or clean up prior threads. <a href="https://www.mnexium.com/docs#history" target="_blank">Docs</a><hr />',
		name: 'resourceHelpHistory',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['history'] } },
	},
	{
		displayName:
			'Manage durable user memory that improves personalization and long-term AI behavior. <a href="https://www.mnexium.com/docs#memories" target="_blank">Docs</a><hr />',
		name: 'resourceHelpMemory',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['memory'] } },
	},
	{
		displayName:
			'Use structured facts and truth state for precise, explainable, machine-friendly reasoning. <a href="https://www.mnexium.com/docs#claims" target="_blank">Docs</a><hr />',
		name: 'resourceHelpClaim',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['claim'] } },
	},
	{
		displayName:
			'Handle structured subject attributes like preferences and identity fields with schema support. <a href="https://www.mnexium.com/docs#profiles" target="_blank">Docs</a><hr />',
		name: 'resourceHelpProfile',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['profile'] } },
	},
	{
		displayName:
			'Persist short-lived workflow context so agents can pause, resume, and continue reliably. <a href="https://www.mnexium.com/docs#agent-state" target="_blank">Docs</a><hr />',
		name: 'resourceHelpState',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['state'] } },
	},
	{
		displayName:
			'Define typed data models so your AI workflows can operate on consistent business objects. <a href="https://www.mnexium.com/docs#records" target="_blank">Docs</a><hr />',
		name: 'resourceHelpRecordSchema',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['recordSchema'] } },
	},
	{
		displayName:
			'Work with structured entities that support filtering and semantic retrieval in automation flows. <a href="https://www.mnexium.com/docs#records" target="_blank">Docs</a><hr />',
		name: 'resourceHelpRecord',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['record'] } },
	},
	{
		displayName:
			'Control reusable instruction layers that shape model behavior by project, subject, or chat scope. <a href="https://www.mnexium.com/docs#system-prompts" target="_blank">Docs</a><hr />',
		name: 'resourceHelpPrompt',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['prompt'] } },
	},
	{
		displayName:
			'Configure extraction policy behavior so memory learning follows your product rules and guardrails. <a href="https://www.mnexium.com/docs#additional-apis" target="_blank">Docs</a><hr />',
		name: 'resourceHelpPolicy',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['memoryPolicy'] } },
	},
	{
		displayName:
			'Inspect request and response traces for debugging, governance, and operational visibility. <a href="https://www.mnexium.com/docs#additional-apis" target="_blank">Docs</a><hr />',
		name: 'resourceHelpAudit',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['audit'] } },
	},
	{
		displayName:
			'Use a direct endpoint call when you need flexibility beyond the typed resource forms. <a href="https://www.mnexium.com/docs" target="_blank">Docs</a><hr />',
		name: 'resourceHelpCustom',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['custom'] } },
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'chatCompletions',
		description: 'Choose the action to run for the selected resource.',
		displayOptions: { show: { resource: ['chat'] } },
		options: [
			{
				name: 'Message a Model',
				value: 'chatCompletions',
				action: 'Message a model',
				description: 'Send a user message with Mnexium memory and continuity controls',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['history'] } },
		options: [
			{
				name: 'List Chats',
				value: 'list',
				action: 'List chats',
				description: 'List chats for a subject',
			},
			{
				name: 'Read Chat',
				value: 'read',
				action: 'Read a chat',
				description: 'Read messages and metadata for a chat',
			},
			{
				name: 'Delete Chat',
				value: 'delete',
				action: 'Delete a chat',
				description: 'Delete a chat by chat ID',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['memory'] } },
		options: [
			{ name: 'List', value: 'list', action: 'List memories', description: 'List memories for a subject' },
			{
				name: 'Search',
				value: 'search',
				action: 'Search memories',
				description: 'Semantic and keyword search across memories',
			},
			{ name: 'Create', value: 'create', action: 'Create a memory', description: 'Create a memory entry' },
			{ name: 'Get', value: 'get', action: 'Get a memory', description: 'Get memory details by memory ID' },
			{ name: 'Update', value: 'update', action: 'Update a memory', description: 'Update an existing memory' },
			{ name: 'Delete', value: 'delete', action: 'Delete a memory', description: 'Delete a memory by ID' },
			{
				name: 'List Superseded',
				value: 'listSuperseded',
				action: 'List superseded memories',
				description: 'List superseded memory versions',
			},
			{ name: 'Restore', value: 'restore', action: 'Restore a memory', description: 'Restore a deleted memory' },
			{
				name: 'List Recall Events',
				value: 'listRecalls',
				action: 'List recall events',
				description: 'List memory recall events for chat or memory context',
			},
			{
				name: 'Get Claims For Memory',
				value: 'getClaims',
				action: 'Get memory claims',
				description: 'Get claims linked to a specific memory',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'getTruth',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['claim'] } },
		options: [
			{ name: 'Get Truth', value: 'getTruth', action: 'Get truth', description: 'Get the resolved truth state' },
			{
				name: 'Get Slot Value',
				value: 'getSlot',
				action: 'Get slot value',
				description: 'Resolve a specific slot value',
			},
			{
				name: 'Get History',
				value: 'getHistory',
				action: 'Get claim history',
				description: 'Read historical changes for a slot',
			},
			{ name: 'List Slots', value: 'listSlots', action: 'List slots', description: 'List available claim slots' },
			{ name: 'Get Graph', value: 'getGraph', action: 'Get graph', description: 'Get claim graph relationships' },
			{ name: 'Create', value: 'create', action: 'Create a claim', description: 'Create a new claim' },
			{ name: 'Get', value: 'get', action: 'Get a claim', description: 'Get a claim by ID' },
			{ name: 'Retract', value: 'retract', action: 'Retract a claim', description: 'Retract a claim by ID' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'get',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['profile'] } },
		options: [
			{ name: 'Get Profile', value: 'get', action: 'Get profile', description: 'Get profile fields for a subject' },
			{
				name: 'Update Fields',
				value: 'update',
				action: 'Update profile fields',
				description: 'Create or update profile fields',
			},
			{
				name: 'Delete Field',
				value: 'deleteField',
				action: 'Delete a profile field',
				description: 'Delete one profile field by key',
			},
			{
				name: 'Get Schema',
				value: 'getSchema',
				action: 'Get profile schema',
				description: 'Get active profile schema',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'get',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['state'] } },
		options: [
			{ name: 'Get', value: 'get', action: 'Get state', description: 'Read stored agent state' },
			{ name: 'Set', value: 'set', action: 'Set state', description: 'Write state value with optional TTL' },
			{ name: 'Delete', value: 'delete', action: 'Delete state', description: 'Delete state value by key' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['recordSchema'] } },
		options: [
			{
				name: 'List Schemas',
				value: 'list',
				action: 'List record schemas',
				description: 'List all record schemas for your project.',
			},
			{
				name: 'Create/Update Schema',
				value: 'createOrUpdate',
				action: 'Create or update record schema',
				description: 'Define or update a schema with type_name and typed fields.',
			},
			{
				name: 'Get Schema',
				value: 'get',
				action: 'Get record schema',
				description: 'Get a record schema by type.',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['record'] } },
		options: [
			{ name: 'List', value: 'list', action: 'List records', description: 'List records by type' },
			{ name: 'Create', value: 'create', action: 'Create a record', description: 'Create a record of a given type.' },
			{ name: 'Get', value: 'get', action: 'Get a record', description: 'Get a record by type and ID.' },
			{ name: 'Update', value: 'update', action: 'Update a record', description: 'Update a record (partial merge).' },
			{ name: 'Delete', value: 'delete', action: 'Delete a record', description: 'Soft-delete a record by ID.' },
			{ name: 'Query', value: 'query', action: 'Query records', description: 'Filter records with exact-match where and server-side sorting.' },
			{ name: 'Search', value: 'search', action: 'Search records', description: 'Semantic search over records using natural language queries.' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['prompt'] } },
		options: [
			{ name: 'List', value: 'list', action: 'List prompts', description: 'List system prompts' },
			{ name: 'Create', value: 'create', action: 'Create a prompt', description: 'Create a system prompt' },
			{ name: 'Get', value: 'get', action: 'Get a prompt', description: 'Get prompt by ID' },
			{ name: 'Update', value: 'update', action: 'Update a prompt', description: 'Update prompt fields' },
			{ name: 'Delete', value: 'delete', action: 'Delete a prompt', description: 'Delete prompt by ID' },
			{
				name: 'Resolve',
				value: 'resolve',
				action: 'Resolve prompt',
				description: 'Resolve effective prompt by scope',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['memoryPolicy'] } },
		options: [
			{ name: 'List', value: 'list', action: 'List memory policies', description: 'List memory policies' },
			{ name: 'Create', value: 'create', action: 'Create memory policy', description: 'Create a memory policy' },
			{ name: 'Get', value: 'get', action: 'Get memory policy', description: 'Get policy by ID' },
			{
				name: 'Update',
				value: 'update',
				action: 'Update memory policy',
				description: 'Update policy configuration',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete memory policy',
				description: 'Delete policy by ID',
			},
			{
				name: 'Resolve',
				value: 'resolve',
				action: 'Resolve memory policy',
				description: 'Resolve effective policy by scope',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'list',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['audit'] } },
		options: [
			{
				name: 'List',
				value: 'list',
				action: 'List audit events',
				description: 'List request/response audit events',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'request',
		description: 'Select the operation to run for this resource.',
		displayOptions: { show: { resource: ['custom'] } },
		options: [
			{
				name: 'Custom API Call',
				value: 'request',
				action: 'API call',
				description: 'Send a direct API request with method, path, headers, query, and optional body',
			},
		],
	},

	// Chat
	{
		displayName: 'Model',
		name: 'chatModel',
		type: 'string',
		default: 'gpt-4.1-mini',
		required: true,
		description: 'Model name to send in the chat request.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'Subject ID',
		name: 'chatSubjectId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		description: 'Optional. If empty, Mnexium creates one automatically',
	},
	{
		displayName: 'Chat ID',
		name: 'chatChatId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		description: 'Optional. If empty, a new chat ID is generated',
	},
	{
		displayName: 'User Message',
		name: 'chatUserMessage',
		type: 'string',
		default: '={{$json.message || $json.text || $json.input || $json.prompt || ""}}',
		required: true,
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		description: 'Text sent as a single user message. Falls back to incoming JSON fields like message/text/input/prompt.',
	},
	{
		displayName: 'Learn',
		name: 'chatLearn',
		type: 'boolean',
		default: true,
		description: 'Whether Mnexium should learn from this message.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'History',
		name: 'chatHistory',
		type: 'boolean',
		default: true,
		description: 'Whether to include prior chat history context.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'Recall',
		name: 'chatRecall',
		type: 'boolean',
		default: false,
		description: 'Whether to recall relevant saved memories.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'Log',
		name: 'chatLog',
		type: 'boolean',
		default: true,
		description: 'Whether to include this request in Mnexium logs.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'Summarize',
		name: 'chatSummarize',
		type: 'options',
		default: 'none',
		description: 'How Mnexium should summarize chat history.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		options: [
			{ name: 'None', value: 'none' },
			{ name: 'Light', value: 'light' },
			{ name: 'Balanced', value: 'balanced' },
			{ name: 'Aggressive', value: 'aggressive' },
		],
	},
	{
		displayName: 'System Prompt',
		name: 'chatSystemPrompt',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		description: 'Optional. Prompt ID or leave empty for auto-resolve',
	},
	{
		displayName: 'Memory Policy',
		name: 'chatMemoryPolicy',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
		description: 'Optional. Memory policy ID or leave empty for auto-resolve',
	},
	{
		displayName: 'Show Advanced Options',
		name: 'chatShowAdvancedOptions',
		type: 'boolean',
		default: false,
		description: 'Show additional chat options.',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'] } },
	},
	{
		displayName: 'Records Recall',
		name: 'chatRecordsRecall',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'], chatShowAdvancedOptions: [true] } },
		description: 'Enable record recall context injection for this chat request.',
	},
	{
		displayName: 'Records Learn Mode',
		name: 'chatRecordsLearnMode',
		type: 'options',
		default: 'off',
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'], chatShowAdvancedOptions: [true] } },
		description: 'Set records extraction behavior for this request.',
		options: [
			{ name: 'Off', value: 'off' },
			{ name: 'Auto', value: 'auto' },
			{ name: 'Force', value: 'force' },
		],
	},
	{
		displayName: 'Records Tables (JSON Array)',
		name: 'chatRecordsTablesJson',
		type: 'json',
		default: '[]',
		displayOptions: {
			show: {
				resource: ['chat'],
				operation: ['chatCompletions'],
				chatShowAdvancedOptions: [true],
				chatRecordsLearnMode: ['auto', 'force'],
			},
		},
		description: 'Optional allowlist of table names used for records extraction (for example ["orders","customers"]).',
	},
	{
		displayName: 'Records Sync',
		name: 'chatRecordsSync',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['chat'],
				operation: ['chatCompletions'],
				chatShowAdvancedOptions: [true],
				chatRecordsLearnMode: ['auto', 'force'],
			},
		},
		description: 'If true, waits for records write completion before returning the response.',
	},
	{
		displayName: 'Regenerate Trial Key',
		name: 'chatRegenerateTrialKey',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['chat'], operation: ['chatCompletions'], chatShowAdvancedOptions: [true] } },
		description: 'Trial users only. Sends mnx.regenerate_key=true for this request.',
	},

	// History
	{
		displayName: 'Subject ID',
		name: 'historySubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['history'], operation: ['list'] } },
	},
	{
		displayName: 'Limit',
		name: 'historyListLimit',
		type: 'number',
		default: 50,
		displayOptions: { show: { resource: ['history'], operation: ['list'] } },
		description: 'Max chats to return. Default 50, max 500',
	},
	{
		displayName: 'Chat ID',
		name: 'historyChatId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the chat id.',
		displayOptions: { show: { resource: ['history'], operation: ['read', 'delete'] } },
	},
	{
		displayName: 'Subject ID (Optional)',
		name: 'historySubjectIdOptional',
		type: 'string',
		default: '',
		description: 'Enter the subject id (optional).',
		displayOptions: { show: { resource: ['history'], operation: ['read', 'delete'] } },
	},
	{
		displayName: 'Limit',
		name: 'historyReadLimit',
		type: 'number',
		default: 200,
		displayOptions: { show: { resource: ['history'], operation: ['read'] } },
		description: 'Max messages to return. Default 200',
	},

	// Memory
	{
		displayName: 'Subject ID',
		name: 'memorySubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['memory'], operation: ['list', 'search', 'listSuperseded', 'create'] } },
	},
	{
		displayName: 'Limit',
		name: 'memoryLimit',
		type: 'number',
		default: 50,
		description: 'Max memories to return.',
		displayOptions: { show: { resource: ['memory'], operation: ['list', 'search', 'listSuperseded', 'listRecalls'] } },
	},
	{
		displayName: 'Offset',
		name: 'memoryOffset',
		type: 'number',
		default: 0,
		description: 'Pagination offset for memory results.',
		displayOptions: { show: { resource: ['memory'], operation: ['list', 'listSuperseded'] } },
	},
	{
		displayName: 'Search Query',
		name: 'memorySearchText',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the search query.',
		displayOptions: { show: { resource: ['memory'], operation: ['search'] } },
	},
	{
		displayName: 'Minimum Score',
		name: 'memorySearchMinScore',
		type: 'number',
		default: 0,
		displayOptions: { show: { resource: ['memory'], operation: ['search'] } },
		description: 'Optional similarity threshold (0-100)',
	},
	{
		displayName: 'Memory ID',
		name: 'memoryId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the memory id.',
		displayOptions: { show: { resource: ['memory'], operation: ['get', 'update', 'delete', 'restore', 'getClaims'] } },
	},
	{
		displayName: 'Text',
		name: 'memoryCreateText',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the text.',
		displayOptions: { show: { resource: ['memory'], operation: ['create'] } },
	},
	{
		displayName: 'Kind',
		name: 'memoryCreateKind',
		type: 'string',
		default: 'preference',
		description: 'Enter the kind.',
		displayOptions: { show: { resource: ['memory'], operation: ['create'] } },
	},
	{
		displayName: 'Importance',
		name: 'memoryCreateImportance',
		type: 'number',
		default: 75,
		displayOptions: { show: { resource: ['memory'], operation: ['create'] } },
		description: '0-100',
	},
	{
		displayName: 'Tags (JSON Array)',
		name: 'memoryCreateTagsJson',
		type: 'json',
		default: '["preference"]',
		description: 'Provide tags as valid JSON for this request.',
		displayOptions: { show: { resource: ['memory'], operation: ['create'] } },
	},
	{
		displayName: 'Metadata (JSON Object)',
		name: 'memoryCreateMetadataJson',
		type: 'json',
		default: '{}',
		description: 'Provide metadata as valid JSON for this request.',
		displayOptions: { show: { resource: ['memory'], operation: ['create'] } },
	},
	{
		displayName: 'Text',
		name: 'memoryUpdateText',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Kind',
		name: 'memoryUpdateKind',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Importance',
		name: 'memoryUpdateImportance',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['update'] } },
		description: 'Optional. Number 0-100',
	},
	{
		displayName: 'Tags (Comma Separated)',
		name: 'memoryUpdateTagsCsv',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['update'] } },
		description: 'Optional. Example: preference,ui,theme',
	},
	{
		displayName: 'Recall Chat ID',
		name: 'memoryRecallsChatId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['listRecalls'] } },
		description: 'Provide chat_id or memory_id',
	},
	{
		displayName: 'Recall Memory ID',
		name: 'memoryRecallsMemoryId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memory'], operation: ['listRecalls'] } },
		description: 'Provide chat_id or memory_id',
	},
	{
		displayName: 'Stats',
		name: 'memoryRecallsStats',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['memory'], operation: ['listRecalls'] } },
		description: 'When true and memory_id is provided, returns aggregate stats',
	},

	// Claim
	{
		displayName: 'Claim ID',
		name: 'claimId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the claim id.',
		displayOptions: { show: { resource: ['claim'], operation: ['get', 'retract'] } },
	},
	{
		displayName: 'Subject ID',
		name: 'claimSubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['claim'], operation: ['getTruth', 'getSlot', 'listSlots', 'getGraph', 'getHistory'] } },
	},
	{
		displayName: 'Include Source',
		name: 'claimIncludeSource',
		type: 'boolean',
		default: true,
		description: 'Whether to include source details in the truth response.',
		displayOptions: { show: { resource: ['claim'], operation: ['getTruth'] } },
	},
	{
		displayName: 'Slot',
		name: 'claimSlot',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the slot.',
		displayOptions: { show: { resource: ['claim'], operation: ['getSlot'] } },
	},
	{
		displayName: 'Slot Filter',
		name: 'claimHistorySlot',
		type: 'string',
		default: '',
		description: 'Enter the slot filter.',
		displayOptions: { show: { resource: ['claim'], operation: ['getHistory'] } },
	},
	{
		displayName: 'Limit',
		name: 'claimLimit',
		type: 'number',
		default: 100,
		description: 'Max claim results to return.',
		displayOptions: { show: { resource: ['claim'], operation: ['getHistory', 'listSlots', 'getGraph'] } },
	},
	{
		displayName: 'Subject ID',
		name: 'claimCreateSubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
	},
	{
		displayName: 'Predicate',
		name: 'claimCreatePredicate',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the predicate.',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
	},
	{
		displayName: 'Object Value',
		name: 'claimCreateObjectValue',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the object value.',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
	},
	{
		displayName: 'Claim Type',
		name: 'claimCreateType',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
		description: 'Optional. Example: fact, preference, trait, event, goal, plan',
	},
	{
		displayName: 'Confidence',
		name: 'claimCreateConfidence',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
		description: 'Optional. 0-1',
	},
	{
		displayName: 'Importance',
		name: 'claimCreateImportance',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
		description: 'Optional. 0-1',
	},
	{
		displayName: 'Tags (JSON Array)',
		name: 'claimCreateTagsJson',
		type: 'json',
		default: '[]',
		description: 'Provide tags as valid JSON for this request.',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
	},
	{
		displayName: 'Source Text',
		name: 'claimCreateSourceText',
		type: 'string',
		default: '',
		description: 'Enter the source text.',
		displayOptions: { show: { resource: ['claim'], operation: ['create'] } },
	},
	{
		displayName: 'Reason',
		name: 'claimRetractReason',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['claim'], operation: ['retract'] } },
		description: 'Optional. Example: user_requested, incorrect, outdated',
	},

	// Profile
	{
		displayName: 'Subject ID',
		name: 'profileSubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['profile'], operation: ['get', 'deleteField'] } },
	},
	{
		displayName: 'Format',
		name: 'profileGetFormat',
		type: 'options',
		default: 'simple',
		description: 'Profile response format.',
		displayOptions: { show: { resource: ['profile'], operation: ['get'] } },
		options: [
			{ name: 'Simple', value: 'simple' },
			{ name: 'Full', value: 'full' },
		],
	},
	{
		displayName: 'Subject ID',
		name: 'profileUpdateSubjectId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['profile'], operation: ['update'] } },
	},
	{
		displayName: 'Updates (JSON Array)',
		name: 'profileUpdatesJson',
		type: 'json',
		default: '[{"field_key":"name","value":"Sarah Chen"}]',
		required: true,
		displayOptions: { show: { resource: ['profile'], operation: ['update'] } },
		description: 'Array of updates. Each item requires field_key and value',
	},
	{
		displayName: 'Field Key',
		name: 'profileFieldKey',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the field key.',
		displayOptions: { show: { resource: ['profile'], operation: ['deleteField'] } },
	},

	// State
	{
		displayName: 'State Key',
		name: 'stateKey',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the state key.',
		displayOptions: { show: { resource: ['state'], operation: ['get', 'set', 'delete'] } },
	},
	{
		displayName: 'Subject ID Header',
		name: 'stateSubjectHeader',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['state'], operation: ['get', 'set', 'delete'] } },
		description: 'Sent as x-subject-id',
	},
	{
		displayName: 'Session ID Header',
		name: 'stateSessionHeader',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['state'], operation: ['get', 'set', 'delete'] } },
		description: 'Optional, sent as x-session-id',
	},
	{
		displayName: 'Value (JSON Object)',
		name: 'stateValueJson',
		type: 'json',
		default: '{"status":"in_progress"}',
		required: true,
		description: 'Provide value as valid JSON for this request.',
		displayOptions: { show: { resource: ['state'], operation: ['set'] } },
	},
	{
		displayName: 'TTL Seconds',
		name: 'stateTtlSeconds',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['state'], operation: ['set'] } },
		description: 'Optional. Leave empty for no expiration',
	},

	// Record schema
	{
		displayName: 'Type',
		name: 'recordSchemaType',
		type: 'string',
		default: '',
		required: true,
		description: 'Unique identifier for the record type (e.g., "account", "deal", "ticket").',
		displayOptions: { show: { resource: ['recordSchema'], operation: ['get'] } },
	},
	{
		displayName: 'Type Name',
		name: 'recordSchemaTypeName',
		type: 'string',
		default: 'account',
		required: true,
		description: 'Unique identifier for the record type (e.g., "account", "deal", "ticket").',
		displayOptions: { show: { resource: ['recordSchema'], operation: ['createOrUpdate'] } },
	},
	{
		displayName: 'Fields (JSON Object)',
		name: 'recordSchemaFieldsJson',
		type: 'json',
		default: '{"name":{"type":"text","required":true}}',
		required: true,
		description: 'Field definitions — keys are field names, values describe the type and constraints.',
		displayOptions: { show: { resource: ['recordSchema'], operation: ['createOrUpdate'] } },
	},
	{
		displayName: 'Display Name',
		name: 'recordSchemaDisplayName',
		type: 'string',
		default: '',
		description: 'Human-readable name for the schema.',
		displayOptions: { show: { resource: ['recordSchema'], operation: ['createOrUpdate'] } },
	},
	{
		displayName: 'Description',
		name: 'recordSchemaDescription',
		type: 'string',
		default: '',
		description: 'Description of what this record type represents.',
		displayOptions: { show: { resource: ['recordSchema'], operation: ['createOrUpdate'] } },
	},

	// Record
	{
		displayName: 'Type',
		name: 'recordType',
		type: 'string',
		default: 'account',
		required: true,
		description: 'Record type name (schema type_name), for example "account".',
		displayOptions: {
			show: { resource: ['record'], operation: ['list', 'create', 'get', 'update', 'delete', 'query', 'search'] },
		},
	},
	{
		displayName: 'Record ID',
		name: 'recordId',
		type: 'string',
		default: '',
		required: true,
		description: 'Record ID to fetch, update, or delete (for example, rec_abc123).',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'update', 'delete'] } },
	},
	{
		displayName: 'Subject ID Header',
		name: 'recordSubjectHeader',
		type: 'string',
		default: '',
		displayOptions: {
			show: { resource: ['record'], operation: ['list', 'create', 'get', 'update', 'delete', 'query', 'search'] },
		},
		description: 'Optional acting subject ID sent as x-subject-id for record access-control checks.',
	},
	{
		displayName: 'Limit',
		name: 'recordListLimit',
		type: 'number',
		default: 50,
		description: 'Max records to return.',
		displayOptions: { show: { resource: ['record'], operation: ['list'] } },
	},
	{
		displayName: 'Offset',
		name: 'recordListOffset',
		type: 'number',
		default: 0,
		description: 'Pagination offset.',
		displayOptions: { show: { resource: ['record'], operation: ['list'] } },
	},
	{
		displayName: 'Data (JSON Object)',
		name: 'recordCreateDataJson',
		type: 'json',
		default: '{"name":"TechCorp"}',
		required: true,
		description: 'Record data matching the schema fields.',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
	},
	{
		displayName: 'Owner ID',
		name: 'recordCreateOwnerId',
		type: 'string',
		default: '',
		description: 'Owner subject ID for access control.',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
	},
	{
		displayName: 'Visibility',
		name: 'recordCreateVisibility',
		type: 'options',
		default: 'public',
		description: 'Access level: "public" (default) or "private".',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
		options: [
			{ name: 'Public', value: 'public' },
			{ name: 'Private', value: 'private' },
		],
	},
	{
		displayName: 'Collaborators (JSON Array)',
		name: 'recordCreateCollaboratorsJson',
		type: 'json',
		default: '[]',
		description: 'Subject IDs that can read/write this record.',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
	},
	{
		displayName: 'Data (JSON Object)',
		name: 'recordUpdateDataJson',
		type: 'json',
		default: '{"status":"resolved"}',
		required: true,
		description: 'Data fields to update (partial merge).',
		displayOptions: { show: { resource: ['record'], operation: ['update'] } },
	},
	{
		displayName: 'Where (JSON Object)',
		name: 'recordQueryWhereJson',
		type: 'json',
		default: '{}',
		description: 'Exact-match filter object (all provided fields must match).',
		displayOptions: { show: { resource: ['record'], operation: ['query'] } },
	},
	{
		displayName: 'Order By',
		name: 'recordQueryOrderBy',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['record'], operation: ['query'] } },
		description: 'Field to sort by (prefix with - for descending).',
	},
	{
		displayName: 'Limit',
		name: 'recordQueryLimit',
		type: 'number',
		default: 50,
		description: 'Max records to return.',
		displayOptions: { show: { resource: ['record'], operation: ['query'] } },
	},
	{
		displayName: 'Offset',
		name: 'recordQueryOffset',
		type: 'number',
		default: 0,
		description: 'Pagination offset.',
		displayOptions: { show: { resource: ['record'], operation: ['query'] } },
	},
	{
		displayName: 'Search Query',
		name: 'recordSearchQuery',
		type: 'string',
		default: '',
		required: true,
		description: 'Natural language search query.',
		displayOptions: { show: { resource: ['record'], operation: ['search'] } },
	},
	{
		displayName: 'Limit',
		name: 'recordSearchLimit',
		type: 'number',
		default: 10,
		description: 'Max results to return.',
		displayOptions: { show: { resource: ['record'], operation: ['search'] } },
	},

	// Prompt
	{
		displayName: 'Prompt ID',
		name: 'promptId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the prompt id.',
		displayOptions: { show: { resource: ['prompt'], operation: ['get', 'update', 'delete'] } },
	},
	{
		displayName: 'Name',
		name: 'promptCreateName',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the name.',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
	},
	{
		displayName: 'Prompt Text',
		name: 'promptCreateText',
		type: 'string',
		default: 'You are a helpful assistant.',
		required: true,
		description: 'Enter the prompt text.',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
	},
	{
		displayName: 'Scope',
		name: 'promptCreateScope',
		type: 'options',
		default: 'project',
		description: 'Scope where this item applies.',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
		options: [
			{ name: 'Project', value: 'project' },
			{ name: 'Subject', value: 'subject' },
			{ name: 'Chat', value: 'chat' },
		],
	},
	{
		displayName: 'Scope ID',
		name: 'promptCreateScopeId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
		description: 'Required if scope is subject or chat',
	},
	{
		displayName: 'Is Default',
		name: 'promptCreateIsDefault',
		type: 'boolean',
		default: false,
		description: 'Whether this prompt is default for its scope.',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
	},
	{
		displayName: 'Priority',
		name: 'promptCreatePriority',
		type: 'number',
		default: 100,
		description: 'Priority value (higher wins).',
		displayOptions: { show: { resource: ['prompt'], operation: ['create'] } },
	},
	{
		displayName: 'Name',
		name: 'promptUpdateName',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['prompt'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Prompt Text',
		name: 'promptUpdateText',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['prompt'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Set Is Default',
		name: 'promptUpdateIsDefaultMode',
		type: 'options',
		default: 'omit',
		description: 'Set default status, or keep unchanged.',
		displayOptions: { show: { resource: ['prompt'], operation: ['update'] } },
		options: [
			{ name: 'No Change', value: 'omit' },
			{ name: 'True', value: 'true' },
			{ name: 'False', value: 'false' },
		],
	},
	{
		displayName: 'Set Is Active',
		name: 'promptUpdateIsActiveMode',
		type: 'options',
		default: 'omit',
		description: 'Set active status, or keep unchanged.',
		displayOptions: { show: { resource: ['prompt'], operation: ['update'] } },
		options: [
			{ name: 'No Change', value: 'omit' },
			{ name: 'True', value: 'true' },
			{ name: 'False', value: 'false' },
		],
	},
	{
		displayName: 'Priority',
		name: 'promptUpdatePriority',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['prompt'], operation: ['update'] } },
		description: 'Optional number',
	},
	{
		displayName: 'Subject ID',
		name: 'promptResolveSubjectId',
		type: 'string',
		default: '',
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['prompt'], operation: ['resolve'] } },
	},
	{
		displayName: 'Chat ID',
		name: 'promptResolveChatId',
		type: 'string',
		default: '',
		description: 'Enter the chat id.',
		displayOptions: { show: { resource: ['prompt'], operation: ['resolve'] } },
	},
	{
		displayName: 'Combined',
		name: 'promptResolveCombined',
		type: 'boolean',
		default: false,
		description: 'Whether to return a combined resolved prompt.',
		displayOptions: { show: { resource: ['prompt'], operation: ['resolve'] } },
	},
	{
		displayName: 'Default Only',
		name: 'promptResolveDefaultOnly',
		type: 'boolean',
		default: false,
		description: 'Whether to include only default prompts.',
		displayOptions: { show: { resource: ['prompt'], operation: ['resolve'] } },
	},

	// Memory policy
	{
		displayName: 'Policy ID',
		name: 'policyId',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the policy id.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['get', 'update', 'delete'] } },
	},
	{
		displayName: 'Name',
		name: 'policyCreateName',
		type: 'string',
		default: '',
		required: true,
		description: 'Enter the name.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
	},
	{
		displayName: 'Policy Text',
		name: 'policyCreateText',
		type: 'string',
		default: 'Extract durable user preferences and constraints.',
		required: true,
		description: 'Enter the policy text.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
	},
	{
		displayName: 'Scope',
		name: 'policyCreateScope',
		type: 'options',
		default: 'project',
		description: 'Scope where this item applies.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
		options: [
			{ name: 'Project', value: 'project' },
			{ name: 'Subject', value: 'subject' },
			{ name: 'Chat', value: 'chat' },
		],
	},
	{
		displayName: 'Scope ID',
		name: 'policyCreateScopeId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
		description: 'Required if scope is subject or chat',
	},
	{
		displayName: 'Is Default',
		name: 'policyCreateIsDefault',
		type: 'boolean',
		default: false,
		description: 'Whether this policy is default for its scope.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
	},
	{
		displayName: 'Priority',
		name: 'policyCreatePriority',
		type: 'number',
		default: 100,
		description: 'Priority value (higher wins).',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
	},
	{
		displayName: 'Config (JSON Object)',
		name: 'policyCreateConfigJson',
		type: 'json',
		default: '{}',
		description: 'Provide config as valid JSON for this request.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['create'] } },
	},
	{
		displayName: 'Name',
		name: 'policyUpdateName',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Policy Text',
		name: 'policyUpdateText',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['update'] } },
		description: 'Optional',
	},
	{
		displayName: 'Set Is Default',
		name: 'policyUpdateIsDefaultMode',
		type: 'options',
		default: 'omit',
		description: 'Set default status, or keep unchanged.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['update'] } },
		options: [
			{ name: 'No Change', value: 'omit' },
			{ name: 'True', value: 'true' },
			{ name: 'False', value: 'false' },
		],
	},
	{
		displayName: 'Set Is Active',
		name: 'policyUpdateIsActiveMode',
		type: 'options',
		default: 'omit',
		description: 'Set active status, or keep unchanged.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['update'] } },
		options: [
			{ name: 'No Change', value: 'omit' },
			{ name: 'True', value: 'true' },
			{ name: 'False', value: 'false' },
		],
	},
	{
		displayName: 'Priority',
		name: 'policyUpdatePriority',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['update'] } },
		description: 'Optional number',
	},
	{
		displayName: 'Subject ID',
		name: 'policyResolveSubjectId',
		type: 'string',
		default: '',
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['resolve'] } },
	},
	{
		displayName: 'Chat ID',
		name: 'policyResolveChatId',
		type: 'string',
		default: '',
		description: 'Enter the chat id.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['resolve'] } },
	},
	{
		displayName: 'Combined',
		name: 'policyResolveCombined',
		type: 'boolean',
		default: false,
		description: 'Whether to return a combined resolved policy.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['resolve'] } },
	},
	{
		displayName: 'Default Only',
		name: 'policyResolveDefaultOnly',
		type: 'boolean',
		default: false,
		description: 'Whether to include only default policies.',
		displayOptions: { show: { resource: ['memoryPolicy'], operation: ['resolve'] } },
	},

	// Audit
	{
		displayName: 'Audit ID',
		name: 'auditId',
		type: 'string',
		default: '',
		description: 'Enter the audit id.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
	},
	{
		displayName: 'Chat ID',
		name: 'auditChatId',
		type: 'string',
		default: '',
		description: 'Enter the chat id.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
	},
	{
		displayName: 'Subject ID',
		name: 'auditSubjectId',
		type: 'string',
		default: '',
		description: 'Enter the subject id.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
	},
	{
		displayName: 'Direction',
		name: 'auditDirection',
		type: 'options',
		default: 'any',
		description: 'Filter by audit event direction.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
		options: [
			{ name: 'Any', value: 'any' },
			{ name: 'Request', value: 'request' },
			{ name: 'Response', value: 'response' },
		],
	},
	{
		displayName: 'Request Type',
		name: 'auditRequestType',
		type: 'options',
		default: 'any',
		description: 'Filter by audit request type.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
		options: [
			{ name: 'Any', value: 'any' },
			{ name: 'Chat', value: 'chat' },
			{ name: 'Responses', value: 'responses' },
			{ name: 'Messages', value: 'messages' },
		],
	},
	{
		displayName: 'Limit',
		name: 'auditLimit',
		type: 'number',
		default: 100,
		description: 'Max audit events to return.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
	},
	{
		displayName: 'Offset',
		name: 'auditOffset',
		type: 'number',
		default: 0,
		description: 'Pagination offset for audit results.',
		displayOptions: { show: { resource: ['audit'], operation: ['list'] } },
	},

	// Custom request-style inputs
	{
		displayName: 'HTTP Method',
		name: 'requestMethod',
		type: 'options',
		default: 'GET',
		description: 'HTTP method for this custom API call.',
		displayOptions: {
			show: {
				resource: ['custom'],
				operation: ['request'],
			},
		},
		options: [
			{ name: 'GET', value: 'GET' },
			{ name: 'POST', value: 'POST' },
			{ name: 'PUT', value: 'PUT' },
			{ name: 'PATCH', value: 'PATCH' },
			{ name: 'DELETE', value: 'DELETE' },
		],
	},
	{
		displayName: 'Path',
		name: 'requestPath',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['custom'],
				operation: ['request'],
			},
		},
		description:
			'Path for the Mnexium endpoint (for example /api/v1/memories). Absolute URLs must be HTTPS on mnexium.com',
	},
	{
		displayName: 'Headers (JSON)',
		name: 'requestHeadersJson',
		type: 'json',
		default: '{}',
		description: 'Provide headers as valid JSON for this request.',
		displayOptions: {
			show: {
				resource: ['custom'],
				operation: ['request'],
			},
		},
	},
	{
		displayName: 'Query Params (JSON)',
		name: 'requestQueryJson',
		type: 'json',
		default: '{}',
		description: 'Provide query params as valid JSON for this request.',
		displayOptions: {
			show: {
				resource: ['custom'],
				operation: ['request'],
			},
		},
	},
	{
		displayName: 'Body (JSON)',
		name: 'requestBodyJson',
		type: 'json',
		default: '{}',
		displayOptions: {
			show: {
				resource: ['custom'],
				operation: ['request'],
				requestMethod: ['POST', 'PUT', 'PATCH', 'DELETE'],
			},
		},
		description: 'Request payload body for non-GET methods',
	},
];
